---
title: Wat zijn breedtegraad en lengtegraad?
hero_image: images/banner.png
description: Uitleg van coördinaten op basis van lengte- en breedtegraad
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "geografie, ruimte"
technologies: "[]"
steps:
  - 
    title: Wat zijn breedtegraad en lengtegraad?
