---
title: Wat zijn breedtegraad en lengtegraad?
hero_image: images/banner.png
description: Uitleg van coördinaten op basis van lengte- en breedtegraad
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: "geography, space"
technologies: "[]"
steps:
  - title: Wat zijn breedtegraad en lengtegraad?
