title: What are Latitude and Longitude?
hero_image: images/banner.png
description: Explanation of corrdinates using latitude and longitude. 
original_url: 
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: "geography, space"
technologies: "[]"
steps:
  - title: What are Latitude and Longitude?
