title: What are latitude and longitude?
hero_image: images/banner.png
description: Explanation of coordinates using latitude and longitude
original_url: 
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: "geography, space"
technologies: "[]"
steps:
  - title: What are latitude and longitude?
