---
title: Hva er breddegrad og lengdegrad?
hero_image: images/banner.png
description: Forklaring av koordinater ved hjelp av breddegrad og lengdegrad
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "geography, space"
technologies: "[]"
steps:
  - 
    title: Hva er breddegrad og lengdegrad?
