---
title: O que são a latitude e longitude?
hero_image: images/banner.png
description: Explicação das coordenadas usando a latitude e longitude
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "geography, space"
technologies: "[]"
steps:
  - title: O que são a latitude e longitude?
