---
title: Što su geografska širina i dužina?
hero_image: images/banner.png
description: Objašnjenje koordinata pomoću geografske širine i dužine
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "geography, space"
technologies: "[]"
steps:
  - title: Što su geografska širina i dužina?
