---
title: Was sind Breiten- und L채ngengrad?
hero_image: images/banner.png
description: Erkl채rung der Koordinaten mit Breiten- und L채ngengrad
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "geography, space"
technologies: "[]"
steps:
  - 
    title: Was sind Breiten- und L채ngengrad?
