---
title: Ce sunt latitudinea și longitudinea?
hero_image: images/banner.png
description: Explicarea coordonatelor folosind latitudinea și longitudinea
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "geography, space"
technologies: "[]"
steps:
  - 
    title: Ce sunt latitudinea și longitudinea?
