---
title: 什麼是緯度和經度？
hero_image: images/banner.png
description: 使用緯度和經度當坐標的解釋
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "地理，空間"
technologies: "[]"
steps:
  - title: 什麼是緯度和經度？
