---
title: '¿Qué son la latitud y la longitud?'
hero_image: images/banner.png
description: Explicación de coordenadas usando latitud y longitud
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "geography, space"
technologies: "[]"
steps:
  - title: '¿Qué son la latitud y la longitud?'
