---
title: Co to jest szerokość i długość geograficzna?
hero_image: images/banner.png
description: Objaśnienie współrzędnych z użyciem szerokości i długości geograficznej
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: "geography, space"
technologies: "[]"
steps:
  - title: Co to jest szerokość i długość geograficzna?
