---
title: Que sont la latitude et la longitude?
hero_image: images/banner.png
description: Explication des coordonnées en utilisant la latitude et la longitude
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "geography, space"
technologies: "[]"
steps:
  - title: Que sont la latitude et la longitude?
