---
title: Enlem ve boylam nedir?
hero_image: images/banner.png
description: Koordinatların enlem ve boylam kullanılarak açıklanması
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: "geography, space"
technologies: "[]"
steps:
  - title: Enlem ve boylam nedir?
